# Generated by Django 6.0.5 on 2026-06-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawrecord',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged')], default='PENDING', max_length=20),
        ),
    ]
